server:
  port: 8080
  servlet:
    context-path: /demo-service
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/DB_Ksmarthome
    username: postgres
    password: 123
  liquibase:
    enabled: 'true'
     
    change-log: classpath:/db/changelog/changelog-master.xml
    parameters:
      liquibase.changelogLockWaitTimeInMinutes: 20
  jpa:
    hibernate:
      ddl-auto: none
 
 